// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xidanhntvdcejcgnlebb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZGFuaG50dmRjZWpjZ25sZWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTQ3OTMsImV4cCI6MjA2MDI3MDc5M30.DqqF6BT29rpho8jX2g9GUy2mNDaukhdj1HqhsHSHqpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);