// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itraiqtgmixtnhuhwknk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cmFpcXRnbWl4dG5odWh3a25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzEwODcsImV4cCI6MjA1OTc0NzA4N30.skTFvL6TemJCwox2ftU4aAM2-NwZkoIONu-usLkjQs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);